config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :new, :create]
  resource :session, only: [:create, :new, :destroy]
  resources :posts, only: [:create, :update, :new, :show, :edit, :destroy]
  resources :subs, only: [:create, :update, :new, :show, :edit, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: 'User',
    inverse_of: :posts

  # remove column for sub_id
  # belongs_to :sub,
  #     primary_key: :id,
  #     foreign_key: :sub_id,
  #     class_name: 'Sub'

end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             not null
#  modetator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :modetator_id,
    class_name: 'User',
    inverse_of: :subs

  # posts and subs are connected through a seperate joined table
  # has_many :posts,
  #   primary_key: :id,
  #   foreign_key: :sub_id,
  #   class_name: 'Post'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :session_token, presence: true, uniqueness: true

  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password

  before_validation :ensure_session_token

  has_many :subs,
    primary_key: :id,
    foreign_key: :modetator_id,
    class_name: 'Sub'

  has_many :posts,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: 'Post'

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!

    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def require_logged_in!
    redirect_to new_session_url unless logged_in?
  end

  def require_logged_out!
    redirect_to new_session_url if logged_in?
  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_logged_in!, except: [:show]
  before_action :require_correct_owner!, only: [:edit, :update]

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash.now[:notices] = ["Successful post!"]
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def new
    @post = Post.new
    render :new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, :user_id)
  end

  def require_correct_owner!
    return if current_user.posts.find_by(id: params[:id])
    render json: 'Forbidden', status: :forbidden

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if user.nil?
      flash.now[:errors] = ["Incorrect username or password"]
      render :new
    else
      login!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

  def new
    render :new
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_logged_in!, except: [:index, :show]
  before_action :require_correct_owner!, only: [:edit, :update]

  def create
    @sub = current_user.subs.new(sub_params)
    if @sub.save
      flash.now[:notices] = ["You just created a new sub"]
      redirect_to subs_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def new
    @sub = Sub.new
    render :new
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to @sub
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def index
    @subs = Sub.all
    render :index
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def require_correct_owner!
    return if current_user.subs.find_by(id: params[:id])
    render json: 'Forbidden', status: :forbidden
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      redirect_to new_session_url
    end
  end

  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :session_token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

    <body>
      <header>
      <nav>
        <h1>Reddit Clone</h1>
        <% if current_user %>
        <p>Welcome <%= current_user.username %> </p>
        <%= button_to "Log Out", session_url, method: :delete %>
        <% else %>
        <p> <%= link_to "Sign Up", new_user_url %> </p>
        <p> or </p>
        <p> <%= link_to "Log In", new_session_url %> </p>
        <% end %>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url %>
<% call_method = post.persisted? ? "PATCH" : "POST" %>

<form
class=""
action="<%= action_url %>"
method="POST">
  <input
  type="hidden"
  name="_method"
  value=" <%= call_method %> ">
  
  <input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">



  <label for="post-title">Title</label>
  <input
  id="pos-title"
  type="text"
  name="post[title]"
  value=" <%= post.title %> ">

  <label for="post-url">URL</label>
  <input
  id="post-url"
  type="text"
  name="post[url]"
  value=" <%= post.url %> ">

  <label for="post-content">Content</label>
  <textarea id="post-content" name="post[content]"> <%= post.content %> </textarea>

  <input type="submit" value="Submit">


</form>

app/views/posts/edit.html.erb
<h1>Edit your post</h1>

<%= render "form", post: @post %>

app/views/posts/new.html.erb
<h1>Create a post</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h1>  <%= @post.title  %> </h1>

<ul>
  <li> <%= @post.url %> </li>
  <li> <%= @post.content %> </li>
</ul>

app/views/subs/_form.html.erb
<% action_url = sub.persisted? ? sub_url(sub) : subs_url  %>
<% call_method = sub.persisted? ? "PATCH" : "POST" %>

<form class="" action=" <%= action_url %> " method="POST">
  <input
  type="hidden"
  name="authenticity_token"
  value=" <%= form_authenticity_token %> ">


  <input 
  type="hidden"
  name="_method"
  value=" <%= call_method %> ">

  <label for="sub-title">Title</label>
  <input id="sub-title" type="text" name="sub[title]" value=" <%= sub.title %> ">

  <label for="sub-description">Description</label>

  <textarea name="sub[description]" id="sub-description"><%=sub.description%> </textarea>

  <input type="submit" value="Submit">

</form>

app/views/subs/edit.html.erb
<h1>Edit your sub</h1>

<%= render "form", sub: @sub %>

app/views/subs/index.html.erb
<h1>SUBS</h1>
<% @subs.each do |sub| %>
<ul>
  <li> <%= sub.title %> </li>
</ul>
<% end %>

app/views/subs/new.html.erb
<h1>Create a sub</h1>

<%= render "form", sub: @sub %>
 

app/views/subs/show.html.erb
<h1> <%= @sub.title %> </h1>
<p>Description</p>
<p> <%= @sub.description %> </p>

app/views/users/new.html.erb
<h1>New User</h1>

<form class="" action=" <%= users_url %>  " method="post">
  <input type="hidden" name="authenticity_token" value=" <% form_authenticity_token %> ">

  <label for="user-username">Username</label>
  <input id="user-username"type="text" name="user[username]">

  <label for="user-password">Password</label>
  <input id="user-password"type="password" name="user[password]" value="">

  <input type="submit" value="Submit">

</form>

app/views/users/show.html.erb
<h1>Hello <%= @user.username %> </h1>